services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped

    environment:
      TZ: America/Sao_Paulo

    ports:
      - "80:80"
      - "81:81"
      - "443:443"

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

    networks:
      - proxy

    labels:
      - "homelab=true"
      - "category=infrastructure"
      - "service=nginx-proxy-manager"

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  proxy:
    external: true
