services:
  seq:
    image: datalust/seq:latest
    container_name: seq

    restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINUSERNAME: "nicolas-santos"
      SEQ_FIRSTRUN_ADMINPASSWORD: "Y9Br4=GxN_C92WpW4D8).'zC"
      TZ: America/Sao_Paulo

    volumes:
      - ./data:/data

    networks:
      - proxy

    labels:
      - "homelab=true"
      - "category=monitoring"
      - "service=seq"

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  proxy:
    external: true

